In [2]:
import pandas as pd

In [6]:
air_df = pd.read_csv("airlines.csv")

In [7]:
air_df

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
0,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2003/06,6,June,2003,1009,1275,3217,17,...,5843,27,23974,30060,61606,68335,118831,518,268764,19474
1,BOS,"Boston, MA: Logan International",2003/06,6,June,2003,374,495,685,3,...,1623,3,7875,9639,20319,28189,24400,99,77167,4160
2,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",2003/06,6,June,2003,296,477,389,8,...,1245,15,6998,8287,13635,26810,17556,278,64480,6201
3,CLT,"Charlotte, NC: Charlotte Douglas International",2003/06,6,June,2003,300,472,735,2,...,1562,14,7021,8670,14763,23379,23804,127,65865,3792
4,DCA,"Washington, DC: Ronald Reagan Washington National",2003/06,6,June,2003,283,268,487,4,...,1100,18,5321,6513,13775,13712,20999,120,52747,4141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4403,SAN,"San Diego, CA: San Diego International",2016/01,1,January,2016,280,397,171,2,...,871,18,5030,6016,15482,23023,6021,79,46206,1601
4404,SEA,"Seattle, WA: Seattle/Tacoma International",2016/01,1,January,2016,357,513,351,2,...,1274,31,8330,9739,25461,32693,11466,73,74017,4324
4405,SFO,"San Francisco, CA: San Francisco International",2016/01,1,January,2016,560,947,2194,2,...,3825,20,8912,13206,43641,72557,153416,66,278610,8930
4406,SLC,"Salt Lake City, UT: Salt Lake City International",2016/01,1,January,2016,338,540,253,3,...,1175,14,7426,8699,32066,33682,8057,57,76978,3116
4407,TPA,"Tampa, FL: Tampa International",2016/01,1,January,2016,410,342,312,2,...,1095,7,4748,5996,22557,21164,11423,37,57774,2593

In [8]:
air_df.info() #Info of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4408 entries, 0 to 4407
Data columns (total 24 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Airport.Code                                         4408 non-null   object
 1   Airport.Name                                         4408 non-null   object
 2   Time.Label                                           4408 non-null   object
 3   Time.Month                                           4408 non-null   int64
 4   Time.Month Name                                      4408 non-null   object
 5   Time.Year                                            4408 non-null   int64
 6   Statistics.# of Delays.Carrier                       4408 non-null   int64
 7   Statistics.# of Delays.Late Aircraft                 4408 non-null   int64
 8   Statistics.# of Delays.National Aviation System      4408 non-null   int64
 9   Statistics.# of Delays.Security                      4408 non-null   int64
 10  Statistics.# of Delays.Weather                       4408 non-null   int64
 11  Statistics.Carriers.Names                            4408 non-null   object
 12  Statistics.Carriers.Total                            4408 non-null   int64
 13  Statistics.Flights.Cancelled                         4408 non-null   int64
 14  Statistics.Flights.Delayed                           4408 non-null   int64
 15  Statistics.Flights.Diverted                          4408 non-null   int64
 16  Statistics.Flights.On Time                           4408 non-null   int64
 17  Statistics.Flights.Total                             4408 non-null   int64
 18  Statistics.Minutes Delayed.Carrier                   4408 non-null   int64
 19  Statistics.Minutes Delayed.Late Aircraft             4408 non-null   int64
 20  Statistics.Minutes Delayed.National Aviation System  4408 non-null   int64
 21  Statistics.Minutes Delayed.Security                  4408 non-null   int64
 22  Statistics.Minutes Delayed.Total                     4408 non-null   int64
 23  Statistics.Minutes Delayed.Weather                   4408 non-null   int64
dtypes: int64(19), object(5)
memory usage: 826.6+ KB

In [11]:
air_df.head() # by default print first 5 lines

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
0,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2003/06,6,June,2003,1009,1275,3217,17,...,5843,27,23974,30060,61606,68335,118831,518,268764,19474
1,BOS,"Boston, MA: Logan International",2003/06,6,June,2003,374,495,685,3,...,1623,3,7875,9639,20319,28189,24400,99,77167,4160
2,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",2003/06,6,June,2003,296,477,389,8,...,1245,15,6998,8287,13635,26810,17556,278,64480,6201
3,CLT,"Charlotte, NC: Charlotte Douglas International",2003/06,6,June,2003,300,472,735,2,...,1562,14,7021,8670,14763,23379,23804,127,65865,3792
4,DCA,"Washington, DC: Ronald Reagan Washington National",2003/06,6,June,2003,283,268,487,4,...,1100,18,5321,6513,13775,13712,20999,120,52747,4141

In [12]:
air_df.head(30) #return 30 lines from TOP

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
0,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2003/06,6,June,2003,1009,1275,3217,17,...,5843,27,23974,30060,61606,68335,118831,518,268764,19474
1,BOS,"Boston, MA: Logan International",2003/06,6,June,2003,374,495,685,3,...,1623,3,7875,9639,20319,28189,24400,99,77167,4160
2,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",2003/06,6,June,2003,296,477,389,8,...,1245,15,6998,8287,13635,26810,17556,278,64480,6201
3,CLT,"Charlotte, NC: Charlotte Douglas International",2003/06,6,June,2003,300,472,735,2,...,1562,14,7021,8670,14763,23379,23804,127,65865,3792
4,DCA,"Washington, DC: Ronald Reagan Washington National",2003/06,6,June,2003,283,268,487,4,...,1100,18,5321,6513,13775,13712,20999,120,52747,4141
5,DEN,"Denver, CO: Denver International",2003/06,6,June,2003,516,323,664,11,...,1611,22,10024,11691,26634,18969,23538,706,75428,5581
6,DFW,"Dallas/Fort Worth, TX: Dallas/Fort Worth Inter...",2003/06,6,June,2003,986,1390,2147,19,...,4798,133,22303,27628,70918,80714,90574,683,263521,20632
7,DTW,"Detroit, MI: Detroit Metro Wayne County",2003/06,6,June,2003,376,371,570,6,...,1395,9,10227,11754,21802,18715,16482,139,60667,3529
8,EWR,"Newark, NJ: Newark Liberty International",2003/06,6,June,2003,322,519,1948,10,...,2921,42,9441,12506,20190,30905,91048,490,150513,7880
9,FLL,"Fort Lauderdale, FL: Fort Lauderdale-Hollywood...",2003/06,6,June,2003,247,256,427,5,...,967,10,3672,4662,12547,14600,14935,141,44303,2080
10,IAD,"Washington, DC: Washington Dulles International",2003/06,6,June,2003,320,295,573,3,...,1256,35,7027,8419,16754,18074,25807,182,65529,4712
11,IAH,"Houston, TX: George Bush Intercontinental/Houston",2003/06,6,June,2003,329,730,1405,15,...,2601,173,12686,15551,21782,43428,56414,577,134182,11981
12,JFK,"New York, NY: John F. Kennedy International",2003/06,6,June,2003,376,226,394,21,...,1046,13,4695,5778,22029,11593,14103,659,50335,1951
13,LAS,"Las Vegas, NV: McCarran International",2003/06,6,June,2003,511,678,624,17,...,1893,6,9821,11759,24293,31043,19561,808,79533,3828
14,LAX,"Los Angeles, CA: Los Angeles International",2003/06,6,June,2003,830,765,842,37,...,2571,10,15780,18462,40089,39655,26162,2559,114434,5969
15,LGA,"New York, NY: LaGuardia",2003/06,6,June,2003,302,338,867,4,...,1604,22,7161,8908,17384,18954,41007,191,82859,5323
16,MCO,"Orlando, FL: Orlando International",2003/06,6,June,2003,368,434,535,3,...,1388,9,6211,7617,17707,26116,18073,56,65140,3188
17,MDW,"Chicago, IL: Chicago Midway International",2003/06,6,June,2003,180,411,311,12,...,951,6,6057,7061,8535,20938,10702,331,42962,2456
18,MIA,"Miami, FL: Miami International",2003/06,6,June,2003,247,210,585,2,...,1105,22,3745,4900,12609,12700,22976,66,52191,3840
19,MSP,"Minneapolis, MN: Minneapolis-St Paul Internati...",2003/06,6,June,2003,428,376,759,9,...,1678,11,10404,12194,27468,20994,23137,529,78259,6131
20,ORD,"Chicago, IL: Chicago O'Hare International",2003/06,6,June,2003,801,982,2947,11,...,4899,38,24997,30195,54296,55855,135851,604,257007,10401
21,PDX,"Portland, OR: Portland International",2003/06,6,June,2003,193,248,213,11,...,684,5,4040,4746,8260,11909,5943,505,27645,1028
22,PHL,"Philadelphia, PA: Philadelphia International",2003/06,6,June,2003,338,565,1083,1,...,2049,20,6917,9069,16478,31005,45538,21,97173,4131
23,PHX,"Phoenix, AZ: Phoenix Sky Harbor International",2003/06,6,June,2003,491,569,664,19,...,1783,10,12158,14008,26512,27458,18673,768,76031,2620
24,SAN,"San Diego, CA: San Diego International",2003/06,6,June,2003,324,349,341,8,...,1052,4,5775,6851,15034,15747,10449,223,43215,1762
25,SEA,"Seattle, WA: Seattle/Tacoma International",2003/06,6,June,2003,448,552,454,28,...,1516,9,7658,9246,22647,28119,13860,1097,68673,2950
26,SFO,"San Francisco, CA: San Francisco International",2003/06,6,June,2003,416,312,1080,14,...,1880,9,8211,10183,22673,17879,45407,1138,90487,3390
27,SLC,"Salt Lake City, UT: Salt Lake City International",2003/06,6,June,2003,363,290,352,15,...,1057,0,9491,10582,16227,13883,10512,556,42863,1685
28,TPA,"Tampa, FL: Tampa International",2003/06,6,June,2003,226,327,524,3,...,1122,11,4256,5401,11012,18558,19078,112,51364,2604
29,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2003/07,7,July,2003,1259,1791,4022,13,...,7452,71,22868,30875,87261,116728,184740,356,418274,29189

In [13]:
air_df.tail() #By default 5 lines from bottom

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
4403,SAN,"San Diego, CA: San Diego International",2016/01,1,January,2016,280,397,171,2,...,871,18,5030,6016,15482,23023,6021,79,46206,1601
4404,SEA,"Seattle, WA: Seattle/Tacoma International",2016/01,1,January,2016,357,513,351,2,...,1274,31,8330,9739,25461,32693,11466,73,74017,4324
4405,SFO,"San Francisco, CA: San Francisco International",2016/01,1,January,2016,560,947,2194,2,...,3825,20,8912,13206,43641,72557,153416,66,278610,8930
4406,SLC,"Salt Lake City, UT: Salt Lake City International",2016/01,1,January,2016,338,540,253,3,...,1175,14,7426,8699,32066,33682,8057,57,76978,3116
4407,TPA,"Tampa, FL: Tampa International",2016/01,1,January,2016,410,342,312,2,...,1095,7,4748,5996,22557,21164,11423,37,57774,2593

In [14]:
air_df.tail(30) #Return 30 lines from bottom

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
4378,TPA,"Tampa, FL: Tampa International",2015/12,12,December,2015,476,480,287,4,...,1290,1,4748,6079,26694,33165,10365,124,75304,4956
4379,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2016/01,1,January,2016,1163,1505,1196,1,...,3984,17,25424,29854,106908,96237,47481,33,262474,11815
4380,BOS,"Boston, MA: Logan International",2016/01,1,January,2016,544,605,396,2,...,1601,9,7216,9100,30973,40085,15118,240,90747,4331
4381,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",2016/01,1,January,2016,290,353,169,4,...,833,11,5711,7174,16995,17467,5905,138,41531,1026
4382,CLT,"Charlotte, NC: Charlotte Douglas International",2016/01,1,January,2016,381,398,467,5,...,1309,8,7292,9224,24040,21783,14306,115,70606,10362
4383,DCA,"Washington, DC: Ronald Reagan Washington National",2016/01,1,January,2016,364,302,318,4,...,1028,10,4817,6455,18888,17199,10534,139,48937,2177
4384,DEN,"Denver, CO: Denver International",2016/01,1,January,2016,614,785,528,2,...,1998,7,15291,17527,46837,51138,19698,47,123179,5459
4385,DFW,"Dallas/Fort Worth, TX: Dallas/Fort Worth Inter...",2016/01,1,January,2016,725,756,619,7,...,2152,15,14158,16572,66941,56121,20564,261,147350,3463
4386,DTW,"Detroit, MI: Detroit Metro Wayne County",2016/01,1,January,2016,422,565,356,0,...,1387,26,7864,9463,36905,42365,15122,33,98431,4006
4387,EWR,"Newark, NJ: Newark Liberty International",2016/01,1,January,2016,425,416,447,1,...,1337,20,6343,8536,22984,27857,23065,40,77405,3459
4388,FLL,"Fort Lauderdale, FL: Fort Lauderdale-Hollywood...",2016/01,1,January,2016,574,561,788,7,...,1979,22,5429,7665,30456,38214,30024,231,103986,5061
4389,IAD,"Washington, DC: Washington Dulles International",2016/01,1,January,2016,120,86,70,0,...,285,3,2003,2533,6576,5453,2309,0,14972,634
4390,IAH,"Houston, TX: George Bush Intercontinental/Houston",2016/01,1,January,2016,448,415,531,3,...,1462,40,9967,11642,32284,26902,25418,152,90829,6073
4391,JFK,"New York, NY: John F. Kennedy International",2016/01,1,January,2016,543,568,451,9,...,1610,21,5893,8014,35204,40771,17425,305,98664,4959
4392,LAS,"Las Vegas, NV: McCarran International",2016/01,1,January,2016,497,744,650,4,...,1983,23,9996,12245,31489,47413,41987,131,128986,7966
4393,LAX,"Los Angeles, CA: Los Angeles International",2016/01,1,January,2016,907,987,1148,9,...,3132,9,12968,16406,57259,66995,43477,447,175743,7565
4394,LGA,"New York, NY: LaGuardia",2016/01,1,January,2016,504,472,661,3,...,1684,16,5804,8035,37571,30389,29284,81,100508,3183
4395,MCO,"Orlando, FL: Orlando International",2016/01,1,January,2016,668,631,724,4,...,2083,6,8368,10730,39310,41841,25297,170,110962,4344
4396,MDW,"Chicago, IL: Chicago Midway International",2016/01,1,January,2016,233,340,207,3,...,831,13,5678,6676,10541,16703,6313,62,37034,3415
4397,MIA,"Miami, FL: Miami International",2016/01,1,January,2016,424,297,714,8,...,1493,46,4374,6088,33545,23808,26050,307,88939,5229
4398,MSP,"Minneapolis, MN: Minneapolis-St Paul Internati...",2016/01,1,January,2016,432,560,481,2,...,1536,7,7947,9585,41753,37283,14638,60,99540,5806
4399,ORD,"Chicago, IL: Chicago O'Hare International",2016/01,1,January,2016,749,993,1228,2,...,3059,14,15141,18605,57731,68443,53301,277,186921,7169
4400,PDX,"Portland, OR: Portland International",2016/01,1,January,2016,159,259,92,3,...,524,5,3580,4143,9374,16451,2993,118,29745,809
4401,PHL,"Philadelphia, PA: Philadelphia International",2016/01,1,January,2016,306,275,199,0,...,805,4,4503,5671,18768,17540,6876,15,46172,2973
4402,PHX,"Phoenix, AZ: Phoenix Sky Harbor International",2016/01,1,January,2016,572,631,449,3,...,1691,7,11150,13035,37417,34111,13544,115,88252,3065
4403,SAN,"San Diego, CA: San Diego International",2016/01,1,January,2016,280,397,171,2,...,871,18,5030,6016,15482,23023,6021,79,46206,1601
4404,SEA,"Seattle, WA: Seattle/Tacoma International",2016/01,1,January,2016,357,513,351,2,...,1274,31,8330,9739,25461,32693,11466,73,74017,4324
4405,SFO,"San Francisco, CA: San Francisco International",2016/01,1,January,2016,560,947,2194,2,...,3825,20,8912,13206,43641,72557,153416,66,278610,8930
4406,SLC,"Salt Lake City, UT: Salt Lake City International",2016/01,1,January,2016,338,540,253,3,...,1175,14,7426,8699,32066,33682,8057,57,76978,3116
4407,TPA,"Tampa, FL: Tampa International",2016/01,1,January,2016,410,342,312,2,...,1095,7,4748,5996,22557,21164,11423,37,57774,2593

In [15]:
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4408 entries, 0 to 4407
Data columns (total 24 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Airport.Code                                         4408 non-null   object
 1   Airport.Name                                         4408 non-null   object
 2   Time.Label                                           4408 non-null   object
 3   Time.Month                                           4408 non-null   int64
 4   Time.Month Name                                      4408 non-null   object
 5   Time.Year                                            4408 non-null   int64
 6   Statistics.# of Delays.Carrier                       4408 non-null   int64
 7   Statistics.# of Delays.Late Aircraft                 4408 non-null   int64
 8   Statistics.# of Delays.National Aviation System      4408 non-null   int64
 9   Statistics.# of Delays.Security                      4408 non-null   int64
 10  Statistics.# of Delays.Weather                       4408 non-null   int64
 11  Statistics.Carriers.Names                            4408 non-null   object
 12  Statistics.Carriers.Total                            4408 non-null   int64
 13  Statistics.Flights.Cancelled                         4408 non-null   int64
 14  Statistics.Flights.Delayed                           4408 non-null   int64
 15  Statistics.Flights.Diverted                          4408 non-null   int64
 16  Statistics.Flights.On Time                           4408 non-null   int64
 17  Statistics.Flights.Total                             4408 non-null   int64
 18  Statistics.Minutes Delayed.Carrier                   4408 non-null   int64
 19  Statistics.Minutes Delayed.Late Aircraft             4408 non-null   int64
 20  Statistics.Minutes Delayed.National Aviation System  4408 non-null   int64
 21  Statistics.Minutes Delayed.Security                  4408 non-null   int64
 22  Statistics.Minutes Delayed.Total                     4408 non-null   int64
 23  Statistics.Minutes Delayed.Weather                   4408 non-null   int64
dtypes: int64(19), object(5)
memory usage: 826.6+ KB

In [18]:
air_df.loc[0:3] #Rows [start_row : end_row]

,Airport.Code,Airport.Name,Time.Label,Time.Month,Time.Month Name,Time.Year,Statistics.# of Delays.Carrier,Statistics.# of Delays.Late Aircraft,Statistics.# of Delays.National Aviation System,Statistics.# of Delays.Security,...,Statistics.Flights.Delayed,Statistics.Flights.Diverted,Statistics.Flights.On Time,Statistics.Flights.Total,Statistics.Minutes Delayed.Carrier,Statistics.Minutes Delayed.Late Aircraft,Statistics.Minutes Delayed.National Aviation System,Statistics.Minutes Delayed.Security,Statistics.Minutes Delayed.Total,Statistics.Minutes Delayed.Weather
0,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2003/06,6,June,2003,1009,1275,3217,17,...,5843,27,23974,30060,61606,68335,118831,518,268764,19474
1,BOS,"Boston, MA: Logan International",2003/06,6,June,2003,374,495,685,3,...,1623,3,7875,9639,20319,28189,24400,99,77167,4160
2,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",2003/06,6,June,2003,296,477,389,8,...,1245,15,6998,8287,13635,26810,17556,278,64480,6201
3,CLT,"Charlotte, NC: Charlotte Douglas International",2003/06,6,June,2003,300,472,735,2,...,1562,14,7021,8670,14763,23379,23804,127,65865,3792